spring:
  application:
    name: app-encapsulation-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8020/eureka/
      
server:
  context-path: /appEncapsulation
  port: 8040

ribbon:  
  ReadTimeout: 50000  
  ConnectTimeout: 50000
