spring:
  application:
    name: client-user-service
  datasource:
    url: jdbc:mysql://localhost:3306/giigle-iot-client-user
    username: root
    password: 
    max-active: 100
    driver-class-name: com.mysql.jdbc.Driver
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 18000000
    max-wait: 60000
    test-while-idle: true
    validation-query: select 1    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8020/eureka/    
server:
  context-path: /clientUser
  port: 8060

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.giigle.message.domain

